#!/usr/bin/python

import sys, os
import subprocess

TOPDIR = subprocess.check_output(['git', 'rev-parse', '--show-toplevel']).strip()
AUDIO2WAV = os.path.join(TOPDIR, 'scripts', 'audio2wav')

def main(dirs):
    for d in dirs:
        for root, dirs, files in os.walk(d):
            for f in files:
                if f.lower().endswith(".wav"):
                    path = os.path.join(root, f)
                    subprocess.check_call([AUDIO2WAV, path])

main(sys.argv[1:])
