#! python

import argparse
import os
import sys

from kokako.score import Detector
from kokako.detectors import  *

# Get the detectors that we know about
detectors = Detector.__subclasses__()
detector_lookup = {}
for d in detectors:
    detector_lookup[d.code] = d()

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-o', 
        '--output',
        default=sys.stdout, 
        type=argparse.FileType('w'),
        help='output file')
    parser.add_argument('detector', help='name of the detector to run')
    parser.add_argument('-p', '--path', help='path to walk over', default='.')
    
    args = parser.parse_args()
    try:
        detector = detector_lookup[args.detector]
    except KeyError:
        msg = "Unknown detector, %s" % args.detector
        raise ValueError, msg

for root, dirs, files in os.walk(args.path):
    for f in files:
        print f
        if f.endswith(".wav"):
            path = os.path.join(root, f)
            print path, detector.score(path)

    
        
        
        

    

